name: Node CI CD

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: git code checkout
              uses: actions/checkout@v3

            - name: env
              run: echo "${{ secrets.ENV }}" > .env

            - name: docker setup
              uses: docker/setup-buildx-action@v3

            - name: docker login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-be:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sparcs-be:cache
                  cache-to: type=inline

    deploy:
        needs: build
        runs-on: ubuntu-20.04
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  debug: true
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-be:latest
                      docker stop sparcs-be || true
                      docker rm sparcs-be || true
                      docker run -d --name sparcs-be -p 8080:4000 \
                        ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-be:latest
